### ISSUE TITLE
Dates do not properly export to SBDF

### ISSUE THREAD

**Issue by jaybazile** [TIBCOSoftware/spotfire-python#23]
The code cannot export the times correctly from the Pandas dataframe when they are the standard datetime64[ns]

See code and screenshot below.  When I open the exported sbdf in this simple example it takes datetime.now() and displays it as year 7933 in the dxp on open.

See the example code and screen shot of results below

import pandas as pd
from spotfire import sbdf
from datetime import datetime

data = [['tom', 10,datetime.now()], ['nick', 15,datetime.now()], ['juli', 14,datetime.now()]]
df = pd.DataFrame(data, columns = ['Name', 'Age','Date'])

sbdf.export_data(df, "df.sbdf")

print(df)
print(df.dtypes)

![image](https://user-images.githubusercontent.com/44701254/155723766-7faee953-ac35-44a3-803f-b86e9b9283a6.png)

**Comment by bbassett-tibco** [comment]
Hi, can you let us know what version of the `spotfire` package or the version of the Spotfire platform you're seeing this issue with?  We know we had a regression with the package version 1.7.0 that was introduced by #18 (which was fixed with 1.7.1, #22), but without knowing the versions you're using, it becomes problematic for us to chase down the issue.

If we don't hear from you by 5/10/2022, we'll assume that this is the 1.7.0 problem, and close the issue.

**Comment by bbassett-tibco** [comment]
Having heard nothing from the submitter, we're going to assume this was in 1.7.0, and was fixed by #22.
